name: pnpm ci

env:
  CI: true

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: verify pnpm
        run: pnpm -v
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: verify node.js
        run: node -v

      - name: restore node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: install dependencies
        run: pnpm install
      - name: downgrade nuxt
        run: pnpm add -D nuxt@3.17.4
      - name: build
        run: |
          pnpm build
          pnpm generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
